version: "3.8"
services:
    php:
        build:
          context: .
        image: base-project/php
        container_name: base-project-php
        restart: always
        volumes:
            - .:/var/www/html/
        ports:
            - "8080:80"
        depends_on:
            - mariadb
        links:
            - mariadb
        networks:
            dev-php-network:
                ipv4_address: 192.168.10.2
    mariadb:
        image: mysql:5.7
        container_name: base-project-mysql
        restart: always
        environment:
            - MYSQL_DATABASE=base_project
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3307:3306"
        networks:
            dev-php-network:
                ipv4_address: 192.168.10.1
networks:
    dev-php-network:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.10.0/16